name: Git Actions Demo
on: [push] # in what event does this workflow run

# What jobs are part of this workflow
jobs:
  action_demo:
    # What type of OS is our pipeline running on
    runs-on: ubuntu-latest
    # for this job what do you want it to do
    steps:
    - run: echo 'Hello World!'
    - run: pwd
    - run: ls
    - run: echo 'Job status is ${{job.status}}'


  clone_demo:
    runs-on: ubunut-latest
    steps:
    - name: Check out Repo
      uses: actions/checkout@v3
    - name: list contents of current directory
      run: ls -al
    - name: Run a python script
      run: python script.py
      
